version: "3.8"
services:
  # jazzbot:
  #   image: node:12
  #   command: bash -c "npm install && node index.js"
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  mysql:
    container_name: jazz_bot_db
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: null
      MYSQL_DATABASE: jazzbot
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - jazz_bot
volumes:
  jazzbot-mysql-data:
networks:
  jazz_bot:
