version: "3.8"
services:
  jazzbot:
    container_name: jazz_bot_app
    image: jazz_bot:latest
    command: /bin/bash -c "/wait && node index.js "
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - "mysql"
  mysql:
    container_name: jazz_bot_db
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=null
      - MYSQL_DATABASE=jazzbot
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
volumes:
  jazzbot-mysql-data:
